[package]
name = "xlsx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0"
chrono = "0.4.19"
rm_rf = "0.6.1"
encoding_rs = "0.8.28"